/**
 * @file test/preparations/lifecycle-model/protocol-maps/prune-sweep.ts
 * @description The Task 9E protocol-preservation map for prune and orphan sweep.
 *
 * Written BEFORE the migration, which is the property that makes a map worth
 * having — see `types.ts`. Every row states what the durable step does TODAY, on
 * `main`, so that a behaviour change during the migration has to change a reviewed
 * record first rather than being discovered afterwards by reading the diff.
 *
 * Two rows deliberately record something the code does that a reader would not
 * want it to do (PLA-MAP-PRN03 waives eligibility on resume; PLA-MAP-PRN11 derives the
 * staging slot twice). They are `preserved` because 9E has not changed them yet,
 * not because they are good. A map that only records the flattering steps cannot
 * be used to detect a regression in the others.
 *
 * A separate file from `reset-quarantine.ts` because that one is already past the
 * repository's 400-line ceiling, not because the two maps are different in kind.
 */

import { at, mapRow, type ProtocolMapRowV1 } from "./types.js";

export const PRUNE_SWEEP_PROTOCOL_MAP: readonly ProtocolMapRowV1[] = [
  mapRow("PLA-MAP-PRN01", "prune",
    "Prune eligibility is decided from the authenticated run record under an INJECTED clock, never `Date.now`: the run must read valid, be terminal, clear the 30-day floor, and — when handed off — have its exact Milestone A bundle re-read and verified, so a byte a surviving bundle still owns is never reclaimed",
    [at("pruneUnitIdFor", "src/preparations/prune-delete.ts"),
     at("pruneEligibility", "src/preparations/retention.ts"),
     at("readPreparationRun", "src/preparations/run-store.ts"),
     at("readOperationManifest", "src/operation-bundles/manifest-store.ts")],
    "authorize",
    "none — pure decision",
    "run bytes live in the active store",
    "unchanged — no mutation yet",
    "re-decided from scratch; the decision is not durable",
    ["PLA-REG-PRN-001", "PLA-REG-PRN-002", "PLA-REG-PRN-004"],
    "preserved",
    undefined,
    "EVIDENCE GAP: the cited tests prove the clock, terminal-state and retention-floor clauses. The handed-off bundle re-read has NO proving test; it is named here so C1b sees it rather than inheriting a row that looks fully evidenced."),

  mapRow("PLA-MAP-PRN02", "prune",
    "The governing key is read before any unit is touched; a key that does not read refuses the operation rather than proceeding under an unverifiable authority",
    [at("readPreparationKey", "src/preparations/key-epoch.ts"),
     at("prunePreparationRunLocked", "src/preparations/retention.ts")],
    "authorize",
    "none — refusal",
    "no unit exists",
    "unchanged",
    "re-read on the next attempt",
    ["refuses a prune outright when the governing key cannot be read"],
    "preserved"),

  mapRow("PLA-MAP-PRN03", "prune",
    "KNOWN RELAXATION, recorded rather than endorsed: eligibility is WAIVED once a unit has a signed planned receipt, so a resumed prune bypasses both the retention floor and the handoff-bundle check. What holds it is that the planned receipt binds kind, unit and operation — and, unlike the quarantine side, it does NOT bind `keyEpochId`",
    [at("pruneUnitStarted", "src/preparations/retention.ts"),
     at("readVerifiedPruneReceipt", "src/preparations/lifecycle-fs/prune-protocol.ts")],
    "authorize",
    "none — decision",
    "a planned receipt may exist without its deletes",
    "unchanged",
    "an started unit continues on its signed plan, which is the intended resume authority",
    ["PLA-REG-PRN-005", "PLA-REG-PRN-009"],
    "preserved",
    undefined,
    "EVIDENCE GAP, stated rather than papered over: the cited tests prove the plan is authority on resume, NOT the eligibility WAIVER itself. No test prunes an ineligible run that already has a started unit. Closing it is C1b work; citing a test that exercises a neighbouring branch is what this file was corrected for. " +
    "The epoch-binding asymmetry against quarantine's `readSettledQuarantineReceipt({keyEpochId})` is sibling set 3 in the 9E plan and is unlanded work, not an accepted difference."),

  mapRow("PLA-MAP-PRN04", "prune",
    "Every unit read or write is preceded by proof that the unit path is absent or a real directory confined to the bound registry, so a redirected unit refuses before any byte is staged",
    [at("assertConfinedPruneUnit", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("runTwoPhaseVerifiedDelete", "src/preparations/prune-delete.ts")],
    "observe",
    "none — refusal",
    "unit path may be a symlink out of the project",
    "unchanged",
    "re-proved on every entry; never cached",
    ["PLA-REG-PRN-008", "PLA-REG-PRN-015"],
    "preserved"),

  mapRow("PLA-MAP-PRN05", "prune",
    "A verified COMPLETED receipt short-circuits the whole operation and is returned as-is, which is what makes prune and sweep idempotent under repetition",
    [at("readVerifiedPruneReceipt", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("runTwoPhaseVerifiedDelete", "src/preparations/prune-delete.ts")],
    "observe",
    "none — read",
    "unit is complete on disk",
    "unchanged",
    "returns the same signed receipt on every subsequent call",
    ["returns the identical completed receipt on a repeated prune instead of re-deleting"],
    "preserved"),

  mapRow("PLA-MAP-PRN06", "prune",
    "The planned receipt is the AUTHORITY on resume: an existing verified plan is reused verbatim and the object set is never re-enumerated, so bytes that appeared after the plan became durable are never swept into it",
    [at("planDelete", "src/preparations/prune-delete.ts"),
     at("pruneAuthority", "src/preparations/prune-delete.ts")],
    "plan",
    "none on resume; on first pass the planned receipt bytes",
    "no plan exists — the operation re-derives one",
    "the plan is durable and governs every later pass",
    "the signed plan is read back and reused; re-enumeration is skipped entirely",
    ["PLA-REG-PRN-005", "PLA-REG-PRN-006", "PLA-REG-PRN-009"],
    "preserved"),

  mapRow("PLA-MAP-PRN07", "prune",
    "The planned object set is the EXACT leaves owned by the run, sorted by logical path, each carrying its byte count and digest — a destructive plan is built only from an inventory that refuses to report a partial scan",
    [at("enumerateRunScope", "src/preparations/quarantine.ts"),
     at("scanForDestructivePlan", "src/preparations/quarantine.ts")],
    "snapshot",
    "none — enumeration",
    "run leaves live in the active store",
    "n/a — read only",
    "not re-run once a plan exists (PLA-MAP-PRN06)",
    ["PLA-REG-PRN-003", "PLA-REG-PRN-010"],
    "preserved",
    undefined,
    "Prune and sweep read the CAPTURED snapshot; the uncaptured enumerators are deleted (§16 clause 3), and both legs now reach the same scanner through the driver's single capture. Safe because a destructive plan's object set provably never reaches the quarantine registry, pinned by destructive-object-scope.test.ts. PLA-REG-PRN-010 exercises the partial-inventory refusal through the SWEEP leg; no prune-leg test plants a partial inventory."),

  mapRow("PLA-MAP-PRN08", "prune",
    "The planned receipt is published create-only and durably, with its parent directory fsynced, so a plan can never be silently replaced by a second one",
    [at("writePruneReceipt", "src/preparations/prune-delete.ts"),
     at("writePruneReceiptBytes", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("signPruneReceipt", "src/preparations/receipts.ts")],
    "plan",
    "the planned receipt leaf",
    "no plan; the operation re-derives",
    "the plan is durable and binding",
    "the existing plan is read and reused; a second create-only write would refuse",
    ["PLA-REG-PRN-005"],
    "preserved",
    undefined,
    "EVIDENCE GAP: PLA-REG-PRN-005 proves an existing durable plan governs a later pass, which is the create-only property's CONSEQUENCE. No test attempts a second create-only write directly."),

  mapRow("PLA-MAP-PRN09", "prune",
    "Each planned leaf is deleted through a stage-then-unlink that is crash-resumable from any of three states — bytes at source, bytes staged, or both names holding the SAME inode — and proves the leaf against the signed inventory before acting, so a substitution between proof and action costs a restored rename rather than the wrong file",
    [at("deletePlannedPruneObject", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("classifyDeleteEnds", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("stageAndDeleteLeaf", "src/utils/planned-bytes.ts"),
     at("deleteStagedLeaf", "src/utils/planned-bytes.ts")],
    "apply/resume",
    "the planned leaf, via its staging slot",
    "the leaf is still at its source name",
    "the leaf is unlinked and its parent fsynced",
    "an absent leaf is a no-op; a staged leaf finishes from staging; two names on one inode unlink the staging copy",
    ["PLA-REG-PRN-007", "PLA-REG-PRN-012", "PLA-REG-PRN-013", "PLA-REG-PRN-014"],
    "preserved"),

  mapRow("PLA-MAP-PRN10", "prune",
    "The completed receipt is published only after every planned delete has returned, and is retained as the signed tombstone — the record that the bytes existed and were reclaimed outlives the bytes",
    [at("runTwoPhaseVerifiedDelete", "src/preparations/prune-delete.ts"),
     at("writePruneReceiptBytes", "src/preparations/lifecycle-fs/prune-protocol.ts")],
    "complete",
    "the completed receipt leaf",
    "deletes are done, unit reads as pending",
    "unit reads as complete and short-circuits",
    "a pending unit re-runs the delete phase, which is idempotent per leaf",
    ["PLA-REG-PRN-003", "PLA-REG-PRN-009", "PLA-REG-PRN-016"],
    "preserved"),

  mapRow("PLA-MAP-PRN11", "prune",
    "CLOSED (§14.5 clause 4): the staging slot name is now derived ONCE, in the path-schema layer below both consumers. It was derived twice from the same formula — privately by the delete executor and publicly by the postcondition classifier — so a drift in either makes the classifier inspect a different file than the executor staged",
    [at("stagedDeleteSlot", "src/preparations/lifecycle-fs/prune-protocol.ts"),
     at("lifecycleStagedDeleteName", "src/preparations/paths.ts")],
    "apply/resume",
    "the staging slot path",
    "n/a — name derivation",
    "n/a",
    "both derivations must agree for a resume to find staged bytes",
    ["PLA-REG-PRN-012"],
    "preserved",
    undefined,
    "§14.5's 'delete superseded staged-delete implementations' names this. Check and executor must share one enumeration primitive — for SWEEP's target that is now literally true (PLA-MAP-SWP03/SWP05); the staging-slot derivation this row covers was the first instance."),

  mapRow("PLA-MAP-SWP01", "sweep",
    "An UNFINISHED sweep is resumed before any new one is derived, because the sweep unit id is a digest of the visible object paths — once the first object is staged it leaves the inventory, so the next pass would derive a DIFFERENT id and strand the original unit with staged bytes and no completed receipt, where nothing else enumerates it",
    [at("sweepUnitIdFor", "src/preparations/prune-delete.ts"),
     at("sweepPreparationOrphansLocked", "src/preparations/retention.ts"),
     at("pendingSweepUnitOf", "src/preparations/retention.ts")],
    "observe",
    "none — selection",
    "a pending unit may hold staged bytes",
    "unchanged",
    "the pending unit's own signed plan is the authority for what it still owes",
    ["PLA-REG-PRN-012", "PLA-REG-PRN-013"],
    "preserved"),

  mapRow("PLA-MAP-SWP02", "sweep",
    "Only a preparation whose run leaf is PROVABLY ABSENT is reclaimed; an owner that merely fails to read is `unavailable`, never `absent`, and is skipped — absence requires a trusted parent",
    [at("enumerateSweepableOrphans", "src/preparations/retention.ts"),
     at("readPreparationManifest", "src/preparations/manifest-store.ts"),
     at("readPreparationRun", "src/preparations/run-store.ts")],
    "snapshot",
    "none — enumeration",
    "orphan bytes live in the active store",
    "n/a — read only",
    "re-enumerated only when no pending unit exists (PLA-MAP-SWP01)",
    ["PLA-REG-PRN-011", "PLA-REG-PRN-017"],
    "preserved"),

  mapRow("PLA-MAP-SWP03", "sweep",
    "An unfinished PRUNE blocks a sweep rather than being swept past, and the selection rule now LITERALLY has one home: `selectSweepTargetUnit` over `projectPendingUnits` is imported by both the mutation gate that authorizes a sweep and the executor that acts, so the two cannot resolve different units. Before this the rule was module-private to `retention.ts` and the gate had no way to reach it at all",
    [at("selectSweepTargetUnit", "src/preparations/lifecycle-snapshot/sweep-target.ts"),
     at("projectPendingUnits", "src/preparations/lifecycle-snapshot/compat.ts"),
     at("pendingSweepUnitOf", "src/preparations/retention.ts"),
     at("projectPruneRegistryHealth", "src/preparations/lifecycle-snapshot/compat.ts"),
     at("withPreparationLifecycleRead", "src/preparations/lifecycle-snapshot/read.ts")],
    "observe",
    "none — refusal",
    "prune registry may hold a pending unit",
    "unchanged",
    "the blocking prune must be completed first; the sweep refuses until then",
    ["blocks a sweep while a genuinely unfinished prune unit is present"],
    "preserved"),

  mapRow("PLA-MAP-SWP04", "sweep",
    "A key that does not read sweeps NOTHING and says WHICH fail-closed answer it is — `key-unavailable`, distinct from `nothing-to-sweep`. Owner classification is impossible without the key, so it fails closed to zero deletions rather than to a partial sweep",
    [at("sweepPreparationOrphansLocked", "src/preparations/retention.ts"),
     at("readPreparationKey", "src/preparations/key-epoch.ts")],
    "authorize",
    "none — no-op",
    "orphan bytes live in the active store",
    "unchanged — nothing deleted",
    "re-attempted once the key reads",
    ["sweeps nothing at all when the key cannot classify owners"],
    "preserved",
    undefined,
    "CLOSED: it returned `null` for BOTH 'cannot classify' and 'nothing to do' — one value, two reasons, which the surface would have reported as an empty project. The outcome is a discriminated union now, so a caller that must tell them apart can."),

  mapRow("PLA-MAP-SWP05", "sweep",
    "The unit a sweep may act on is decided ONCE, by the gate, under the acquired lock, and carried to the executor — which compares it against its OWN capture and refuses divergence rather than retargeting. Sweep is the one destructive operation whose target is an observation rather than a function of its request, so a pre-lock scan would authorize one unit while the executor's capture selected another",
    [at("selectSweepTargetUnit", "src/preparations/lifecycle-snapshot/sweep-target.ts"),
     at("sweepPreparationOrphansLocked", "src/preparations/retention.ts")],
    "authorize",
    "none — refusal",
    "the gate's authorized unit and this capture's unit may differ",
    "unchanged — the comparison precedes the key read and all planning",
    "a divergence is reported, not resolved: nothing is deleted either way",
    ["refuses when its own capture resolves a different unit"],
    "preserved"),
];
