/**
 * @file test/preparations/lifecycle-model/protocol-maps/reset-quarantine.ts
 * @description The total protocol-preservation map for the Task 9D migration:
 * project reset, per-run quarantine, purge, intent supersession, and the shared
 * two-phase custody driver they all reach.
 *
 * Required by authority design V2 §5.1 before Task 9D implementation begins.
 * Derived by walking the write orderings in the production modules named in each
 * row's `seam`, not by transcribing any design prose. Where a row's crash
 * classification is stated, it is the classification the SNAPSHOT reports for that
 * on-disk shape, not an informal description.
 *
 * ONE KNOWN GAP is recorded rather than papered over: a reset that crashes at the
 * post-mint seam with its continuation token lost has no exit. Accepted as a known
 * defect by the dated scope decision `plans/2026-07-30-stranded-reset-scope-decision.md`
 * §3.2, which also authorises 9D to proceed. See PLA-MAP-R12.
 */

import { at, mapRow, type ProtocolMapRowV1 } from "./types.js";

export const RESET_QUARANTINE_PROTOCOL_MAP: readonly ProtocolMapRowV1[] = [
  // ------------------------------------------ supersession (reached from reset pass one)
  mapRow("PLA-MAP-R01", "supersession",
    "An explicit supersede request clears every provably intent-only unit BEFORE eligibility is judged, so a healthy key cannot make a stale marker permanent",
    [at("supersedeIntentOnlyUnitsLocked", "src/preparations/reset-intent-supersession.ts"), at("recordResetIntent", "src/preparations/reset.ts")],
    // note: called from
    "authorize",
    "removes bytes/ when strictly empty, then reset-intent.json; marker-last is the commit point",
    "unit intent-only, blocking lifecycle mutation",
    "unit gone; nothing else changed",
    "re-running supersession is a no-op on an absent unit",
    ["PLA-REG-RST-004", "supersedes a pending intent only when explicitly asked, invalidating its token"],
    "preserved"),

  mapRow("PLA-MAP-R02", "supersession",
    "Supersession refuses any unit whose continuation leg materialised key material or custody, leaving it completely untouched",
    [at("classifyUnit", "src/preparations/reset-intent-supersession.ts")],
    "authorize",
    "none — refusal",
    "unit materialized",
    "unchanged",
    "n/a — no state written",
    ["PLA-CASE-071", "PLA-CASE-072"],
    "preserved"),

  mapRow("PLA-MAP-R03", "supersession",
    "Supersession clears a unit only when the caller supplied the exact confirmation that unit's recorded reason demands",
    [at("supersedeIntentOnlyUnitsLocked", "src/preparations/reset-intent-supersession.ts")],
    "authorize",
    "none — skip",
    "unit intent-only under a different reason",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-004"],
    "preserved"),

  mapRow("PLA-MAP-R21", "supersession",
    "Supersession classifies a candidate unit from one read-only observation, and treats any unreadable or non-confined unit as not supersedable rather than guessing",
    [at("observeResetIntentUnit", "src/preparations/lifecycle-fs/reset-operations.ts"),
     at("classifyUnit", "src/preparations/reset-intent-supersession.ts")],
    "observe",
    "none — read only",
    "unit unchanged",
    "unit unchanged",
    "re-observe; the read is repeatable and holds no state",
    ["PLA-REG-RST-004", "refuses to supersede using the wrong confirmation class"],
    "preserved",
    undefined,
    "Fails closed: every unreadable shape returns `unavailable`, which classifies as NOT supersedable."),

  mapRow("PLA-MAP-R22", "supersession",
    "Clearing an intent-only unit removes its empty bytes directory FIRST and its intent marker LAST, so the marker's absence is the single durable signal that the unit was superseded",
    [at("clearResetIntentUnit", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "apply/resume",
    "the unit's empty bytes/ directory, then its reset-intent marker",
    "marker present, unit still supersedable",
    "marker absent; the unit is thereafter classified materialized and left untouched",
    "re-run: a crash between the two removals leaves the marker present with bytes/ already gone, which still classifies intent-only, so the same clear repeats and completes",
    ["PLA-REG-RST-004", "supersedes a pending intent only when explicitly asked, invalidating its token"],
    "preserved",
    undefined,
    "Marker-last ordering is the crash contract; reversing it would make a half-cleared unit indistinguishable from a materialized one."),

  // ------------------------------------------------- the driver's own sequence
  mapRow("PLA-MAP-D01", "shared",
    "Eligibility and a SEALED plan draft are produced first — under one read-only capture when the adapter consumes it (reset), or with no capture at all when it does not (per-run quarantine) — then any lease closes, an operation-bound permit is minted, materialization runs under it, and the custody engine receives that same draft and permit",
    [at("runLifecycleCustodyOperation", "src/preparations/lifecycle-driver.ts"), at("sealCustodyPlan", "src/preparations/lifecycle-driver.ts"), at("mintLifecycleMutationPermit", "src/preparations/lifecycle-mutation-permit.ts")],
    "snapshot",
    "none of its own — it sequences the phases that do; the permit is a runtime brand, not a durable record",
    "no operation in flight",
    "the custody engine holds the same draft and permit the capture justified",
    "an interrupted operation re-runs from the top with a fresh draft and a fresh permit. Scoped to DRIVER-OWNED state only: the durable legs deliberately do carry across attempts — an authenticated plan is reused verbatim (S02) and a staged key is reused verbatim (R14)",
    ["makes the custody protocol itself refuse without a permit", "refuses an edit made after the capture closed"],
    "strengthened"),

  // ---------------------------------------------------------------- reset: pass one
  mapRow("PLA-MAP-R04", "reset",
    "A reset is eligible only when the active key is missing or unreadable; a healthy key is refused",
    [at("readPreparationKey", "src/preparations/key-epoch.ts")],
    // note: through the reset eligibility branch
    "authorize",
    "none — refusal",
    "key healthy",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-007", "PLA-REG-RST-013"],
    "preserved"),

  mapRow("PLA-MAP-R05", "reset",
    "The reason is derived from the observed key state, and each reason demands its own distinct confirmation",
    [at("requiredResetConfirmation", "src/preparations/receipts.ts")],
    "authorize",
    "none — refusal on mismatch",
    "key absent or unreadable",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-006"],
    "preserved"),

  mapRow("PLA-MAP-R06", "reset",
    "A second pass one is refused while ANY intent marker remains, so two live intents can never exist",
    [at("settlePendingIntents", "src/preparations/reset.ts")],
    "authorize",
    "none — refusal",
    "a unit holds reset-intent.json",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-003", "PLA-REG-RST-012"],
    "preserved"),

  mapRow("PLA-MAP-R07", "reset",
    "An unreadable quarantine registry refuses rather than assuming no pending reset exists",
    [at("settlePendingIntents", "src/preparations/reset.ts"), at("resetIntentLeafPresence", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "snapshot",
    "none — refusal",
    "registry or unit unreadable",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-017"],
    "preserved"),

  mapRow("PLA-MAP-R08", "reset",
    "Pass one mints a one-time continuation secret, records ONLY its digest in an unsigned marker, and returns the secret to the caller",
    [at("recordResetIntent", "src/preparations/reset.ts"), at("resetContinuationDigest", "src/preparations/receipts.ts"), at("writeResetUnitLeaf", "src/preparations/lifecycle-fs/reset-operations.ts")],
    // note: resetContinuationDigest; writeResetUnitLeaf(intent) (reset-operations.ts)
    "plan",
    "creates the unit root and writes reset-intent.json create-only, mode 0600",
    "no unit",
    "unit awaiting-continuation; lifecycle mutation blocked, GC held",
    "the operator continues with the secret; without it the unit is intent-only and supersedable (PLA-MAP-R01)",
    ["PLA-REG-RST-001"],
    "preserved"),

  // ---------------------------------------------------------------- reset: pass two
  mapRow("PLA-MAP-R09", "reset",
    "Pass two runs ONLY on presentation of the one-time secret, bound to the exact named unit; the marker must self-bind to the directory it was read from",
    [at("openContinuation", "src/preparations/reset.ts"), at("matchesContinuationDigest", "src/preparations/receipts.ts")],
    // note: matchesContinuationDigest
    "authorize",
    "none — refusal",
    "unit awaiting-continuation",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-005", "PLA-REG-RST-015"],
    "preserved"),

  mapRow("PLA-MAP-R10", "reset",
    "A completed reset short-circuits on proof of full semantic settlement — completed kind, project-reset scope, this unit, this reason, and the epoch the active key actually holds",
    [at("readCompletedReset", "src/preparations/reset.ts"), at("readSettledQuarantineReceipt", "src/preparations/quarantine-move.ts")],
    "observe",
    "none — read only",
    "reset completed, crash material may remain",
    "unchanged",
    "returns the same completed result; cleanup then re-runs idempotently",
    ["PLA-REG-RST-016"],
    "preserved"),

  mapRow("PLA-MAP-R11", "reset",
    "A healthy active key at rerun is trusted ONLY when it byte-matches this unit's staged pending key, authenticated under the secret; any other key refuses rather than quarantining live authority",
    [at("assessResetKey", "src/preparations/reset.ts"), at("readAuthenticatedPendingKey", "src/preparations/reset.ts"), at("verifyPendingResetKey", "src/preparations/receipts.ts")],
    // note: verifyPendingResetKey
    "authorize",
    "none — refusal",
    "key healthy and foreign",
    "unchanged",
    "n/a",
    ["PLA-REG-RST-014"],
    "preserved"),

  mapRow("PLA-MAP-R12", "reset",
    "KNOWN GAP: a crash after the mint with the continuation token lost leaves the unit holding both crash leaves while the key is healthy — every exit refuses and staging throws",
    [at("materializeResetKey", "src/preparations/reset.ts")],
    // note: its publish leg, with the token unavailable
    "apply/resume",
    "none — the state is already durable; no step can advance it",
    "post-mint, token held: resumable",
    "post-mint, token lost: NO EXIT",
    "none in product. Escalation only; the pre-mint variant's runbook must NOT be applied here",
    ["reports/2026-07-30-stranded-reset-operator-runbook.md §2.2"],
    "rejected",
    "plans/2026-07-30-stranded-reset-scope-decision.md §3.2 — accepted as a known defect; exit owned by a future bounded recovery task"),

  mapRow("PLA-MAP-R13", "reset",
    "The forced flow moves the unreadable key leaf into unit custody byte-for-byte BEFORE minting, or fails closed; only a PROVED absence means a prior attempt already moved it",
    [at("moveOldKeyIntoUnit", "src/preparations/reset.ts"), at("moveOldPreparationKey", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "apply/resume",
    "renames the key leaf to bytes/old-key; fsyncs both parents",
    "key present but unreadable",
    "key absent; bytes/old-key holds the only copy of the prior epoch key",
    "a proved-absent key leaf is treated as already moved and the flow continues",
    ["PLA-REG-RST-020"],
    "preserved"),

  mapRow("PLA-MAP-R14", "reset",
    "The fresh key MATERIAL is staged unit-bound and HMAC-authenticated under the continuation secret BEFORE it is ever published, so a crash leaves the exact key recoverable",
    [at("stagePendingResetKey", "src/preparations/reset.ts"), at("signPendingResetKey", "src/preparations/receipts.ts"), at("writeResetUnitLeaf", "src/preparations/lifecycle-fs/reset-operations.ts")],
    // note: signPendingResetKey; writeResetUnitLeaf(pending-key)
    "plan",
    "writes pending-reset-key.json create-only, mode 0600 — PLAINTEXT key bytes",
    "unit awaiting-continuation, no staged key",
    "unit awaiting-continuation with staged key; still unpublished",
    "a rerun with the secret reuses the staged key verbatim rather than minting a second one",
    ["PLA-REG-RST-019"],
    "preserved"),

  mapRow("PLA-MAP-R15", "reset",
    "The staged key is published to the active slot create-only; a collision is tolerated ONLY when the installed key is this exact staged key",
    [at("publishActiveResetKey", "src/preparations/reset.ts"), at("publishActivePreparationKey", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "apply/resume",
    "writes the active key leaf create-only, mode 0600",
    "key absent",
    "key healthy and equal to the staged key",
    "an identical installed key is an idempotent resume; any other key is a single-epoch race and throws",
    ["PLA-REG-RST-018"],
    "preserved"),

  mapRow("PLA-MAP-R16", "reset",
    "Project scope is every active preparation leaf across workspaces PLUS every durable leaf under the prune registry, because prune contents are authenticated under the epoch being destroyed and no later sweep could verify them",
    [at("enumerateProjectScope", "src/preparations/quarantine.ts"), at("enumeratePruneUnitContents", "src/preparations/quarantine.ts"), at("enumeratePruneCustodyLeaves", "src/preparations/lifecycle-fs/quarantine-operations.ts")],
    "snapshot",
    "none — enumeration; refuses on a non-authoritative inventory",
    "n/a",
    "n/a",
    "re-enumerated on resume only when no authenticated plan exists (see PLA-MAP-S02)",
    ["PLA-REG-RST-009", "PLA-REG-RST-010"],
    "preserved"),

  mapRow("PLA-MAP-R17", "reset",
    "The reset attests which OTHER quarantine units it retires, pairing each with its completed receipt's exact digest, over unit ids taken from the driver's single capture rather than a second registry enumeration — and REFUSES outright when that listing is not authoritative, because attesting a retirement set from a subset would silently under-retire",
    [at("retirableUnitsFromRead", "src/preparations/reset.ts"), at("projectQuarantineUnits", "src/preparations/lifecycle-snapshot/compat.ts"), at("retirableUnitsFrom", "src/preparations/quarantine-move.ts")],
    // note: over and
    "plan",
    "retiredUnits[] inside the signed receipt content",
    "other units completed under the dying epoch",
    "those units read historical rather than pending",
    "the authenticated plan is reused verbatim on resume, so the retirement set cannot drift once planned; before planning, a non-authoritative listing refuses rather than attesting a partial set",
    ["PLA-CASE-036", "refuses to attest a retirement set from a non-authoritative listing"],
    "preserved"),

  mapRow("PLA-MAP-R18", "reset",
    "Once the reset settles durably, its crash material is removed plaintext-key first and intent marker last, each delete reconfined at delete time — in the DRIVER'S completion phase, under the same permit as the operation that earned it",
    [at("completeLifecycleCustodyOperation", "src/preparations/lifecycle-driver.ts"), at("removeResetCrashLeaves", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "complete",
    "unlinks pending-reset-key.json, then reset-intent.json; fsyncs the parent",
    "completed receipt durable; crash leaves present",
    "unit holds only its receipts and bytes; no longer pending",
    "re-running tolerates a proved-absent leaf, so a partial cleanup completes",
    ["PLA-REG-RST-008"],
    "preserved"),

  // ------------------------------------------------------------ quarantine: per run
  mapRow("PLA-MAP-Q01", "quarantine",
    "A run is quarantined only when it is EXACTLY integrity-invalid, the key is healthy, and the destructive confirmation is present",
    [at("quarantinePreparationRunLocked", "src/preparations/quarantine.ts")],
    "authorize",
    "none — refusal",
    "run valid, key missing, or confirmation absent",
    "unchanged",
    "n/a",
    ["PLA-REG-QTN-003"],
    "preserved"),

  mapRow("PLA-MAP-Q02", "quarantine",
    "The unit id is deterministic per run, so a re-run resumes the same unit rather than creating a second",
    [at("perRunQuarantineUnitId", "src/preparations/quarantine.ts")],
    "plan",
    "selects the unit path; no bytes",
    "n/a",
    "n/a",
    "identical id on every attempt — this is what makes the operation idempotent",
    ["PLA-REG-QTN-002"],
    "preserved"),

  mapRow("PLA-MAP-Q03", "quarantine",
    "Quarantined bytes stop counting as active while remaining byte-identical in custody — reached through the driver, not by the adapter calling the custody engine itself",
    [at("quarantinePreparationRunLocked", "src/preparations/quarantine.ts"), at("runLifecycleCustodyOperation", "src/preparations/lifecycle-driver.ts")],
    "apply/resume",
    "moves each object into bytes/ preserving content",
    "run active and integrity-invalid",
    "run's bytes in custody; active totals exclude them",
    "see PLA-MAP-S01..S05",
    ["PLA-REG-QTN-001", "PLA-REG-QTN-009"],
    "preserved"),

  // ------------------------------------------------- shared two-phase custody driver
  mapRow("PLA-MAP-S01", "shared",
    "A verified completed receipt short-circuits the whole operation, making it idempotent",
    [at("runTwoPhaseQuarantine", "src/preparations/quarantine-move.ts"), at("readVerifiedReceipt", "src/preparations/quarantine-move.ts")],
    "observe",
    "none — read only",
    "operation complete",
    "unchanged",
    "returns the existing receipt; no bytes move twice",
    ["PLA-REG-QTN-002"],
    "preserved"),

  mapRow("PLA-MAP-S02", "shared",
    "The plan is signed and durable BEFORE any byte moves, and an existing authenticated plan is reused verbatim rather than re-enumerated",
    [at("planPhase", "src/preparations/quarantine-move.ts")],
    "plan",
    "mkdir bytes/; writes quarantine-planned.json create-only, HMAC'd under the governing key",
    "no plan",
    "plan durable; the exact object set is now authority",
    "resume reads the existing plan and continues from it, so the moved set cannot drift",
    ["PLA-REG-QTN-007"],
    "preserved"),

  mapRow("PLA-MAP-S03", "shared",
    "Objects are moved byte-preserving, exactly the set the signed plan names and no other",
    [at("movePhase", "src/preparations/quarantine-move.ts")],
    "apply/resume",
    "renames/links each planned object into bytes/",
    "plan durable, objects at source",
    "objects at destination; sources unlinked",
    "a partially moved set resumes from the plan; already-moved objects are recognised rather than re-moved",
    ["PLA-REG-QTN-010", "PLA-REG-QTN-008"],
    "preserved"),

  mapRow("PLA-MAP-S04", "shared",
    "Postconditions are verified against the plan before completion — byte count and digest per object, and a live source beside planned destination bytes refuses",
    [at("verifyPhase", "src/preparations/quarantine-move.ts")],
    // note: postconditions.ts
    "verify",
    "none — read only; refuses",
    "objects moved",
    "unchanged",
    "n/a — refusal leaves the operation resumable",
    ["PLA-REG-QTN-008"],
    "preserved"),

  mapRow("PLA-MAP-S05", "shared",
    "The completed receipt is written create-only and is the single durable signal of settlement",
    [at("writeReceipt", "src/preparations/quarantine-move.ts")],
    "complete",
    "writes quarantine-completed.json create-only, HMAC'd",
    "objects moved and verified",
    "unit terminal; purge becomes available",
    "a second attempt short-circuits at PLA-MAP-S01",
    ["PLA-REG-QTN-004"],
    "preserved"),

  mapRow("PLA-MAP-Q04", "quarantine",
    "The moved set is the EXACT leaves owned by this run, enumerated from a destructive traversal that refuses a non-authoritative inventory — planning from a subset would quarantine less than the operator authorised. Registry completeness comes from the driver's capture; only ACTIVE storage is walked, because a snapshot carries unit state and never per-leaf detail",
    [at("enumerateRunScope", "src/preparations/quarantine.ts"), at("scanForDestructivePlan", "src/preparations/quarantine.ts"),
     at("scanActivePreparationStore", "src/preparations/orphan-scan.ts"),
     at("scanPreparationOrphans", "src/preparations/orphan-scan.ts")],
    // note: over
    "snapshot",
    "none — enumeration; refuses when the capture or the active scan reports problems",
    "run leaves live in the active store",
    "n/a — read only",
    "re-enumerated only when no authenticated plan exists; an existing plan is authority (PLA-MAP-S02)",
    ["PLA-REG-QTN-001"],
    "preserved"),

  mapRow("PLA-MAP-Q05", "quarantine",
    "The fresh-start precondition is waived only on proof of SEMANTIC settlement; a merely present completed file must never waive it",
    [at("quarantineUnitStarted", "src/preparations/quarantine-move.ts"), at("assertIntegrityInvalid", "src/preparations/quarantine.ts")],
    "authorize",
    "none — refusal",
    "unit may hold a copied receipt",
    "unchanged",
    "a genuinely settled unit resumes; a forged one refuses",
    ["PLA-REG-QTN-002", "PLA-REG-RST-016"],
    "preserved"),

  mapRow("PLA-MAP-Q06", "quarantine",
    "Only a run reading EXACTLY integrity-invalid may be quarantined; the run record is read through the authenticated store rather than inferred",
    [at("readPreparationRun", "src/preparations/run-store.ts"), at("assertIntegrityInvalid", "src/preparations/quarantine.ts")],
    // note: via
    "authorize",
    "none — refusal",
    "run valid or unreadable",
    "unchanged",
    "n/a",
    ["PLA-REG-QTN-003"],
    "preserved"),

  mapRow("PLA-MAP-S06", "shared",
    "Each planned object is captured with its exact byte count and digest before the plan is signed, so the completed receipt can be re-verified against reality",
    [at("captureLifecycleScopedObject", "src/preparations/lifecycle-fs/quarantine-operations.ts"), at("scopedLeafObject", "src/preparations/quarantine.ts")],
    "observe",
    "none — observation; the values enter the signed plan",
    "objects at source",
    "n/a — read only",
    "an authenticated plan carries the captured values verbatim on resume",
    ["PLA-REG-QTN-009"],
    "preserved"),

  mapRow("PLA-MAP-R19", "reset",
    "Pending-intent detection enumerates the quarantine registry, and an unreadable registry refuses rather than reporting none",
    [at("listQuarantineUnits", "src/preparations/quarantine-move.ts"), at("settlePendingIntents", "src/preparations/reset.ts")],
    // note: via
    "snapshot",
    "none — enumeration; refuses on an unreadable registry",
    "registry may hold reset units",
    "n/a — read only",
    "n/a",
    ["PLA-REG-RST-017"],
    "preserved"),

  mapRow("PLA-MAP-R20", "reset",
    "Reset unit leaves are read through one bounded, confined reader that distinguishes absent from unavailable, never a caller-selected path",
    [at("readResetUnitLeaf", "src/preparations/lifecycle-fs/reset-operations.ts")],
    "observe",
    "none — bounded read",
    "leaf present, absent, or unreadable",
    "n/a — read only",
    "n/a",
    ["PLA-REG-RST-005", "PLA-REG-RST-012"],
    "preserved"),

  // ------------------------------------------------------------------------- purge
  mapRow("PLA-MAP-P01", "purge",
    "Purge requires a completed receipt that authenticates for this exact unit, kind and epoch, plus the destroy confirmation",
    [at("purgeQuarantineUnitLocked", "src/preparations/quarantine.ts")],
    "authorize",
    "none — refusal",
    "unit incomplete or confirmation absent",
    "unchanged",
    "n/a",
    ["PLA-REG-QTN-005", "PLA-REG-QTN-006"],
    "preserved"),

  mapRow("PLA-MAP-P02", "purge",
    "Purge destroys ONLY the objects the settled receipt names, and retains the receipt tombstone",
    [at("destroyQuarantineUnitBytes", "src/preparations/lifecycle-fs/quarantine-operations.ts"),
     at("destroySettledQuarantineUnit", "src/preparations/quarantine-destroy.ts")],
    "complete",
    "unlinks each named object leaf; receipts remain",
    "unit terminal with bytes",
    "unit terminal without bytes; tombstone retained",
    "re-running tolerates proved-absent objects",
    ["PLA-REG-QTN-004"],
    "preserved"),
];
