/**
 * Version-locked support for the standard compiler CLI and MCP composition.
 * Exports existing command handlers and bounded read/presentation helpers;
 * registration and process orchestration stay in the standard distribution.
 * Each handler retains its existing operator, review and apply checks.
 */
export { parseInputPairs, parseJsonObject, parseInputJsonObject } from "./cli/input-parsers.js";
export { classifyRun, workflowStatus, workflowStatusForWorkflow } from "./workflow-history/status.js";
export type { RunClassification, RunStatus } from "./workflow-history/status.js";
export { confirmHumanGateInteractively, nonInteractiveHumanGateIo } from "./local-workflow-host/human-gate-confirm.js";
export type { HumanGateIo } from "./local-workflow-host/human-gate-confirm.js";
export { confineProjectionPath } from "./local-workflow-host/projection.js";
export type { ArtifactRef } from "./artifacts/ref.js";
export { resolveArtifactRef, declaresArtifactTypes } from "./artifacts/resolve.js";
export { addProviderOption, applyProviderOption } from "./cli/provider-option.js";
export type { ProviderOption } from "./cli/provider-option.js";
export { runExitCodeCommand } from "./cli/shared.js";
export { artifactWriteCommand, artifactVerifyCommand } from "./commands/artifact.js";
export type { ArtifactWriteOptions, ArtifactVerifyOptions } from "./commands/artifact.js";
export { default as compileCommand } from "./commands/compile.js";
export { connectorListCommand, connectorRunCommand } from "./commands/connector.js";
export type { ConnectorRunOptions } from "./commands/connector.js";
export { default as contextCommand } from "./commands/context.js";
export type { ContextCommandOptions } from "./commands/context.js";
export { default as evalCommand, evalCacheClearCommand, evalCacheShowCommand, evalReportCommand, evalHistoryCommand, evalJudgementsCommand } from "./commands/eval.js";
export { default as exportCommand } from "./commands/export.js";
export { default as importCommand } from "./commands/import.js";
export { default as ingestSessionCommand } from "./commands/ingest-session.js";
export { default as ingestCommand, ingestSource } from "./commands/ingest.js";
export { default as lintCommand } from "./commands/lint.js";
export { default as nextCommand } from "./commands/next.js";
export { operationCancelCommand } from "./commands/operation/cancel.js";
export { operationResumeCommand, operationCompensateCommand } from "./commands/operation/drive.js";
export { operationInspectCommand } from "./commands/operation/inspect.js";
export { operationListCommand } from "./commands/operation/list.js";
export { preparationCancelCommand } from "./commands/preparation/cancel.js";
export { preparationFailCommand } from "./commands/preparation/fail.js";
export { preparationGateCommand } from "./commands/preparation/gate.js";
export { preparationListCommand } from "./commands/preparation/list.js";
export { preparationPauseCommand } from "./commands/preparation/pause.js";
export { preparationPruneCommand } from "./commands/preparation/prune.js";
export { preparationRecoverCommand } from "./commands/preparation/recovery.js";
export { RESET_CONFIRM_DESCRIPTION, RESET_TOKEN_DESCRIPTION, preparationResetCommand } from "./commands/preparation/reset.js";
export { preparationResumeCommand } from "./commands/preparation/resume.js";
export { preparationShowCommand } from "./commands/preparation/show.js";
export { preparationPreviewCommand, preparationStageCommand } from "./commands/preparation/stage.js";
export { preparationSweepCommand } from "./commands/preparation/sweep.js";
export { productInvokeCommand, productResumeCommand, productPreviewCommand } from "./commands/product/action.js";
export { productApplyCommand } from "./commands/product/apply.js";
export type { ProductApplyOptions } from "./commands/product/apply.js";
export { productInitCommand } from "./commands/product/init.js";
export type { ProductActionOptions } from "./commands/product/inputs.js";
export { productActivateCommand, productInstallCommand } from "./commands/product/package.js";
export type { ProductPackageOptions } from "./commands/product/package.js";
export { productStatusCommand } from "./commands/product/status.js";
export type { ProductStatusOptions } from "./commands/product/status.js";
export { profileShow, profileValidate, profileDiff, profileInit } from "./commands/profile.js";
export { default as queryCommand, generateAnswer, assertQuerySaveOptions } from "./commands/query.js";
export { default as quickstartCommand } from "./commands/quickstart.js";
export { recoverCommand } from "./commands/recover.js";
export { default as refreshCommand } from "./commands/refresh.js";
export { default as reviewApproveCommand } from "./commands/review-approve.js";
export { default as reviewListCommand } from "./commands/review-list.js";
export { default as reviewRejectCommand } from "./commands/review-reject.js";
export { default as reviewShowCommand } from "./commands/review-show.js";
export { rmCommand } from "./commands/rm.js";
export { registerRulesCommand } from "./commands/rules-register.js";
export { schemaInitCommand, schemaShowCommand } from "./commands/schema.js";
export { stateResetCommand } from "./commands/state-reset.js";
export { default as statusCommand } from "./commands/status.js";
export { templatePublishAddCommand, templatePublishBuildCommand, templatePublishInitCommand, templatePublishRevokeCommand, templatePublishRotateCommand, templatePublishVerifyCommand } from "./commands/template-publish.js";
export type { TemplatePublishAddOptions, TemplatePublishBuildOptions, TemplatePublishInitOptions, TemplatePublishRevokeOptions, TemplatePublishRotateOptions, TemplatePublishVerifyOptions } from "./commands/template-publish.js";
export { templateRemoteInspectCommand, templateSearchCommand, templateVerifyCommand } from "./commands/template-remote.js";
export type { RemoteOutputOptions, TemplateSearchOptions } from "./commands/template-remote.js";
export { templateTapAddCommand, templateTapForgetCommand, templateTapListCommand, templateTapRefreshCommand, templateTapRemoveCommand } from "./commands/template-tap.js";
export type { TapAddOptions, TapForgetOptions, TapOutputOptions } from "./commands/template-tap.js";
export { templateInspectCommand, templateInitCommand, templateListCommand, templateStatusCommand, templateUpdateCommand } from "./commands/template.js";
export type { TemplateInitOptions, TemplateStatusOptions, TemplateUpdateOptions } from "./commands/template.js";
export { default as viewCommand } from "./commands/view.js";
export { default as visualizeCommand } from "./commands/visualize.js";
export type { VisualizeOptions } from "./commands/visualize.js";
export { default as watchCommand } from "./commands/watch.js";
export { parseConcurrencyFlag } from "./compiler/concurrency.js";
export { compileAndReport } from "./compiler/index.js";
export { buildContextPack } from "./context/build.js";
export { runEval, DEFAULT_SAMPLE_SIZE } from "./eval/index.js";
export { loadPreviousReport, loadHistory } from "./eval/stats.js";
export { runOkfExport } from "./export/okf/run.js";
export { runOkfImport } from "./import/run.js";
export { lint } from "./linter/index.js";
export { readPageRecord } from "./pages/read.js";
export { loadNonDefaultProfile } from "./profile/block.js";
export { isSlugSafe } from "./profile/identity.js";
export { readBoundedFromHandle } from "./profile/templates/publish/bounded-read.js";
export type { AppendRelationInput } from "./relations/store.js";
export { pickSearchRefs, loadSelectedRefs } from "./search/retrieval.js";
export { listSelectedSourceFiles } from "./sources/scan.js";
export { collectStatus } from "./status/collect.js";
export type { TrustDecision } from "./trust/decision.js";
export { readCappedNoFollow } from "./utils/confined-read.js";
export { ENV_VERBOSE, MAX_WORKFLOW_SUBMIT_FILE_BYTES, CONCEPTS_DIR, INDEX_FILE, QUERIES_DIR, SOURCES_DIR, STATE_FILE } from "./utils/constants.js";
export { safeReadFile, parseFrontmatter } from "./utils/markdown.js";
export { applyLanguageOption } from "./utils/output-language.js";
export * as output from "./utils/output.js";
export { setVerbose, withQuiet } from "./utils/output.js";
export { confineUnderRoot } from "./utils/path-confine.js";
export { ensureCompileProviderAvailable, ensureProviderAvailable } from "./utils/provider-guard.js";
export { applySourcesSectionOption } from "./utils/sources-section.js";
export { readStateClassified } from "./utils/state.js";
export { processTerminalLineIo } from "./utils/terminal-line.js";
